# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9ddc22140e9c71d13c65b84a9c04f4af40220e04d3267d92c8c0977f90dbd2236a18aec98df9fec71740b70b8b4c0afb345040b397596b670b490c62f45f82f

test:
  secret_key_base: 60e04db91f7545d871666c29003b07bcce0a9f9a7d3f673f892488a7a9575f12e3c6436505015c2dae04eda69eaa42f907de106808f1f481c499ed2143f163c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
